const section = [
  {
    name: "Frontend",
    tags: [
      "React",
      "JavaScript",
      "CSS",
      "HTML",
      "TailwindCSS",
      "Redux",
      "Socket.io",
    ],
    trending_questions: [],
  },
  {
    name: "Backend",
    tags: [
      "Node.js",
      "Express",
      "Flask",
      "Django",
      "Spring Boot",
      "REST API",
      "GraphQL",
    ],
  },
  {
    name: "Database",
    tags: [
      "MongoDB",
      "MySQL",
      "PostgreSQL",
      "SQLite",
      "Redis",
      "Firebase",
      "Cassandra",
    ],
  },
  {
    name: "DevOps",
    tags: [
      "Docker",
      "Kubernetes",
      "Jenkins",
      "GitHub Actions",
      "Terraform",
      "AWS",
      "CI/CD",
    ],
  },
  {
    name: "Mobile Development",
    tags: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "Java",
      "Ionic",
      "Xamarin",
    ],
  },
  {
    name: "Data Science & ML",
    tags: [
      "Python",
      "NumPy",
      "Pandas",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "Matplotlib",
    ],
  },
  {
    name: "Cybersecurity",
    tags: [
      "Ethical Hacking",
      "Cryptography",
      "Network Security",
      "OWASP",
      "Firewalls",
      "Kali Linux",
      "SIEM",
    ],
  },
  {
    name: "Cloud Computing",
    tags: [
      "AWS",
      "Azure",
      "Google Cloud",
      "Serverless",
      "Cloud Functions",
      "Load Balancing",
      "S3",
    ],
  },
  {
    name: "Blockchain & Web3",
    tags: [
      "Solidity",
      "Ethereum",
      "Smart Contracts",
      "Web3.js",
      "Metamask",
      "NFTs",
      "DeFi",
    ],
  },
  {
    name: "UI/UX Design",
    tags: [
      "Figma",
      "Adobe XD",
      "Sketch",
      "Wireframing",
      "Prototyping",
      "User Research",
      "Accessibility",
    ],
  },
];
export default section;
