const staticSections = [
  {
    name: "Maths",
    icon: "🔢",
    tags: [
      "Algebra",
      "Calculus",
      "Geometry",
      "Trigonometry",
      "Statistics",
      "Probability",
      "Arithmetic",
      "Logic",
      "Equations",
      "Functions",
      "ProblemSolving",
      "Quantitative",
      "LinearAlgebra",
      "DiscreteMath",
      "NumberTheory",
    ],
    slug: "maths",
  },
  {
    name: "Science",
    icon: "🔬",
    tags: [
      "Physics",
      "Chemistry",
      "Biology",
      "Astronomy",
      "Geology",
      "Ecology",
      "Biochemistry",
      "Experiments",
      "ScientificMethod",
      "Thermodynamics",
      "Quantum",
      "Genetics",
      "EarthScience",
      "AppliedScience",
      "MaterialScience",
    ],
    slug: "science",
  },
  {
    name: "Social Science",
    icon: "🌍",
    tags: [
      "History",
      "Geography",
      "Civics",
      "Economics",
      "Sociology",
      "PoliticalScience",
      "Psychology",
      "Anthropology",
      "Culture",
      "GlobalStudies",
      "PublicAdministration",
      "Law",
      "UrbanStudies",
      "Ethics",
      "Philosophy",
    ],
    slug: "social-science",
  },
  {
    name: "English",
    icon: "🗣️",
    tags: [
      "Grammar",
      "Vocabulary",
      "Literature",
      "Writing",
      "Reading",
      "Communication",
      "Poetry",
      "Prose",
      "Spelling",
      "Fluency",
      "CreativeWriting",
      "AcademicWriting",
      "PublicSpeaking",
      "Idioms",
      "Syntax",
    ],
    slug: "english",
  },
  {
    name: "Share Market",
    icon: "📈",
    tags: [
      "Stocks",
      "Trading",
      "Investment",
      "FinancialAnalysis",
      "Bonds",
      "MutualFunds",
      "Commodities",
      "Forex",
      "RiskManagement",
      "MarketNews",
      "TechnicalAnalysis",
      "FundamentalAnalysis",
      "Portfolio",
      "IPOs",
      "Derivatives",
    ],
    slug: "share-market",
  },
  {
    name: "Computer Science",
    icon: "💻",
    tags: [
      "Programming",
      "WebDevelopment",
      "MobileApps",
      "DataScience",
      "AI",
      "MachineLearning",
      "CyberSecurity",
      "CloudComputing",
      "Databases",
      "Algorithms",
      "SoftwareEngineering",
      "Networking",
      "BigData",
      "DevOps",
      "UX/UI",
    ],
    slug: "computer-science",
  },
];

export default staticSections;
